FROM dolfinx/lab:stable

# Set the working directory
WORKDIR /root/shared

# Copy the contents of the current directory to the container
COPY . .

# Install additional Python libraries
RUN pip install cadquery perlin-noise

# Expose the port that JupyterLab runs on
EXPOSE 8888

# Start JupyterLab using the entrypoint command from the base image
ENTRYPOINT ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--allow-root"]
